/* eslint-disable */
export default{
    about:{
      "url-api":"https://dog.ceo/dog-api/documentation/random",
      "categories":[
        "spaniel",
        "australian-shepherd",
        "finnish-lapphund",
        "terrier",
        "doberman",
        "waterdog-spanish",
        "mountain-swiss",
        "labrador",
        "bullterrier",
        "chihuahua",
        "husky"
      ]
    },
    dogs:[
      {
          "id":"1",
          "image": "img/spaniel1.png",
          "breed":"spaniel"
        },
      {
          "id":"2",
          "image":"img/australian-shepherd1.png",
          "breed":"australian-shepherd"
        },
      {
          "id":"3",
          "image":"img/finnish-lapphund.png",
          "breed":"finnish-lapphund"
        },
      {
          "id":"4",
          "image":"img/terrier1.png",
          "breed":"terrier"
        },
      {
          "id":"5",
          "image":"img/spaniel2.png",
          "breed":"spaniel"
        },
      {
          "id":"6",
          "image":"img/terrier2.png",
          "breed":"terrier"
        },
      {
          "id":"7",
          "image":"img/doberman1.png",
          "breed":"doberman"
        },
      {
          "id":"8",
          "image":"img/australian-shepherd2.png",
          "breed":"australian-shepherd"
        },
      {
          "id":"9",
          "image":"img/spaniel3.png",
          "breed":"spaniel"
        },
      {
          "id":"10",
          "image":"img/terrier3.png",
          "breed":"terrier"
        },
      {
          "id":"11",
          "image":"img/waterdog-spanish.png",
          "breed":"waterdog-spanish"
        },
      {
          "id":"12",
          "image":"img/mountain-swiss.png",
          "breed":"mountain-swiss"
        },
      {
          "id":"13",
          "image":"img/terrier4.png",
          "breed":"terrier"
        },
      {
          "id":"14",
          "image":"img/labrador1.png",
          "breed":"labrador"
        },
      {
          "id":"15",
          "image":"img/bullterrier.png",
          "breed":"bullterrier"
        },
      {
          "id":"16",
          "image":"img/doberman2.png",
          "breed":"doberman"
        },
      {
          "id":"17",
          "image":"img/spaniel4.png",
          "breed":"spaniel"
        },
      {
          "id":"18",
          "image":"img/chihuahua1.png",
          "breed":"chihuahua"
        },
      {
          "id":"19",
          "image":"img/chihuahua2.png",
          "breed":"chihuahua"
        },
      {
          "id":"20",
          "image":"img/husky.png",
          "breed":"husky"
        },
      {
          "id":"21",
          "image":"img/labrador2.png",
          "breed":"labrador"
        }
    ]
  }
